---
name: Generic Issue
description: "Choose this only if you can reproduce the issue in a clean, generic environment. If the issue requires extensive logs, flares, or debugging, please use the 'Support Request or Feature Request' option."
title: "[BUG] "
labels: bug,pending
body:
  - type: input
    attributes:
      label: Helm chart name
      description: "Name of the helm chart affected by this bug"
      placeholder: datadog
    validations:
      required: true
  - type: input
    attributes:
      label: Helm chart version
      description: "Version(s) of the helm chart affected by this bug"
      placeholder: 3.X.Y
    validations:
      required: true

  - type: textarea
    attributes:
      label: Bug Report
      description: Please add a clear and concise description of the bug here. What happened and what you expected.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Reproduction Steps
      description: Please add anything here to help us reproduce the problem.
    validations:
      required: false

  - type: textarea
    attributes:
      label: Kubernetes
      description: Please add any useful information about the Kubernetes environment, such as version and cloud provider.
    validations:
      required: false

  - type: input
    attributes:
      label: Helm
      description: "Provide your Helm version (`helm version`)"
      placeholder: v3.X.Y
    validations:
      required: false

  - type: input
    attributes:
      label: Other environment details
      description: "Provide any additional environment information."
    validations:
      required: false
