name: Release Charts

on:
  push:
    branches:
      - main
    paths:
      - 'charts/**'

permissions: {}

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      # https://github.com/helm/chart-releaser-action
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
        with:
          fetch-depth: 0
      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
      - name: Run chart-releaser
        id: release-chart
        uses: helm/chart-releaser-action@be16258da8010256c6e82849661221415f031968 # v1.5.0
        env:
          CR_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
          CR_SKIP_EXISTING: true # Ignore chart changes when version was not updated (documentation)
          CR_SKIP_UPLOAD: true
      - name: echo chart-releaser outputs
        run: |
          echo "the new chart version is ${{ steps.release-chart.outputs.chart_version }}"
          echo "changed charts: ${{ steps.release-chart.outputs.changed_charts }}"
